// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMuWR5Sj4KLAks03Pg5aDGBbTA2WzZV5Y',
    appId: '1:743105149664:web:6beede190f4ebcbb8b2e85',
    messagingSenderId: '743105149664',
    projectId: 'tam-an-app',
    authDomain: 'tam-an-app.firebaseapp.com',
    storageBucket: 'tam-an-app.firebasestorage.app',
    measurementId: 'G-NXQ87BH0KK',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMuWR5Sj4KLAks03Pg5aDGBbTA2WzZV5Y',
    appId: '1:743105149664:web:badf68d00147dbf58b2e85',
    messagingSenderId: '743105149664',
    projectId: 'tam-an-app',
    authDomain: 'tam-an-app.firebaseapp.com',
    storageBucket: 'tam-an-app.firebasestorage.app',
    measurementId: 'G-2RJ5K211C2',
  );
}
